config/routes.rb
Rails.application.routes.draw do

	#get "welcome/say_hello" => "welcome#say"
	#get "welcome"=>"welcome#index"

	#root :to =>"welcome#index"

	resources :events
	#match ':controller(/:action(/:id(.:format)))', :via => :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_event, :only => [:show, :edit, :update, :destroy]

	def index
		@event = Event.page(params[:page]).per(5)
	end

	def new
		@event = Event.new
	end

	def create
		raise
		@event = Event.new(event_params)
		if @event.save
        	redirect_to events_url
        	flash[:notice] = "event was successfully created"
        else
        	render :action =>:new
        end

	end

	def show
		@page_title = @event.name
	end

	def edit
	end

	def update
		raise
		if @event.update(event_params)
        	redirect_to event_url(@event)
        	flash[:notice] = "event was successfully updated"
        else
        	render :action => :edit
        end
	end

	def destroy
		@event.destroy
		flash[:notice] = "event was successfully deleted"
		redirect_to events_url
	end

	private

	def event_params
		params.require(:event).permit(:name, :description)
	end

	def set_event
		@event = Event.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def say
	end
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :url =>{ :controller =>'events', :action => 'create' } do |f| %>
	<%= f.label :name, "Name" %>
	<%= f.text_field :name %>

	<%= f.label :description, "Description" %>
	<%= f.text_area :description %>

	<% if @event.errors.any? %>
		<ul>
			<%@event.errors.full_message.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end%>

<% end %>

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event), :method => :patch do |f| %>
	<%= render :partial => 'form', :locals =>{ :f => f} %>

	<%= f.submit "Update" %>

	<% end %>

app/views/events/index.html.erb
<ul>
<% @event.each do |event| %>
	<li>
		<%= event.name %>
	<%= link_to 'Show', event_path(event) %>
	<%= link_to 'Edit', edit_event_path(event) %>
	<%= button_to 'Delete', event_path(event), :method => :delete, :data =>{:confirm => "Are you sure?"} %>
	</li>
	<% end %>
</ul>

<%= link_to 'New Event', :controller=> 'events', :action => 'new' %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path, :method => :post  do |f| %>
	<%= render :partial => 'form', :locals =>{ :f => f} %>
	<%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>

<p>
	<%= link_to 'Back to index', events_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
    	<%= @page_title || "Event application" %>
    </title>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p style="color: green"><%= flash[:notice] %></p>
    <p style="color: red"><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<p>
	Hola! It's <%= Time.now %> 
</p>

<p>
	<%= link_to 'Hello!', welcome_say_hello_path %>
</p>

app/views/welcome/say.html.erb
<h1>
	Hello, world!
</h1>
<p>
	<%= link_to "Home",root_path %>
</p>